const data = {
  products: [
    {
      _id: '1',
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 1000,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: 'Lascote Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 2200,
      countInStock: 0,
      brand: 'Lascote',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 780,
      countInStock: 14,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 18,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 890,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.3,
      numReviews: 8,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 980,
      countInStock: 12,
      brand: 'Adidas',
      rating: 3.9,
      numReviews: 13,
      description: 'high quality product',
    },
  ],
};

export default data;
